//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicines
    {
        public int id { get; set; }
        public int pokupatel { get; set; }
        public string prodav { get; set; }
        public string recrpt { get; set; }
        public string prodaja { get; set; }
    
        public virtual Buyer Buyer { get; set; }
    }
}
