//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int id { get; set; }
        public string data { get; set; }
        public string col { get; set; }
        public int id_rec { get; set; }
        public int id_prod { get; set; }
    
        public virtual Recipe Recipe { get; set; }
        public virtual Seller Seller { get; set; }
    }
}
